"""er-project baseline — full new schema (35 tables, docs/er-project.md).

Fresh start: replaces the pre-redesign 0001–0006 chain. UUID PKs
(gen_random_uuid), TIMESTAMPTZ timestamps, CHECK-constrained enums, and the
mutual-exclusion vincoli (polar_points owner, devices owner) as CHECKs.

Revision ID: 0001
Revises:
Create Date: 2026-07-03
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('default_sensors', sa.JSON(), nullable=True),
    sa.Column('parser_key', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("category IN ('boat_tracker', 'wearable')", name=op.f('ck_device_types_category_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_types')),
    sa.UniqueConstraint('name', name=op.f('uq_device_types_name'))
    )
    op.create_table('permissions',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('key', name=op.f('uq_permissions_key'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('terms_and_conditions', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('profile_image_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('inactive', 'active', 'deleted')", name=op.f('ck_users_status_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    # users -> images FK added after images exists (use_alter breaks the
    # users<->images cycle; inline use_alter FKs are skipped by CREATE TABLE).
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('wind_stations',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_station_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('station_type', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("provider IN ('noaa_ndbc', 'noaa_metar', 'open_meteo', 'custom_device')", name=op.f('ck_wind_stations_provider_allowed')),
    sa.CheckConstraint("station_type IN ('buoy', 'metar', 'forecast_grid', 'custom_device')", name=op.f('ck_wind_stations_station_type_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wind_stations')),
    sa.UniqueConstraint('provider', 'external_station_id', name=op.f('uq_wind_stations_provider_external_station_id'))
    )
    op.create_table('auth_refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('prev_id', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['prev_id'], ['auth_refresh_tokens.id'], name=op.f('fk_auth_refresh_tokens_prev_id_auth_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_refresh_tokens'))
    )
    op.create_index(op.f('ix_auth_refresh_tokens_family_id'), 'auth_refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_auth_refresh_tokens_token_hash'), 'auth_refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_refresh_tokens_user_id'), 'auth_refresh_tokens', ['user_id'], unique=False)
    op.create_table('files',
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'processed', 'deleted')", name=op.f('ck_files_status_allowed')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_files_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_files_deleted_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_table('images',
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'processed', 'deleted')", name=op.f('ck_images_status_allowed')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_images_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_images_deleted_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    op.create_foreign_key(op.f('fk_users_profile_image_id_images'), 'users', 'images', ['profile_image_id'], ['id'], ondelete='SET NULL')
    op.create_table('imports',
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('raw_ref', sa.String(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processed', 'failed')", name=op.f('ck_imports_status_allowed')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_imports_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imports'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name=op.f('uq_role_permissions_role_id_permission_id'))
    )
    op.create_table('wind_observations',
    sa.Column('wind_station_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('twd_deg', sa.Float(), nullable=True),
    sa.Column('tws_kts', sa.Float(), nullable=True),
    sa.Column('gust_kts', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['wind_station_id'], ['wind_stations.id'], name=op.f('fk_wind_observations_wind_station_id_wind_stations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wind_observations')),
    sa.UniqueConstraint('wind_station_id', 'observed_at', name=op.f('uq_wind_observations_wind_station_id_observed_at'))
    )
    op.create_table('boat_classes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['logo_id'], ['images.id'], name=op.f('fk_boat_classes_logo_id_images'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boat_classes')),
    sa.UniqueConstraint('name', name=op.f('uq_boat_classes_name'))
    )
    op.create_table('clubs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address_line_1', sa.String(), nullable=True),
    sa.Column('address_line_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state_province', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('logo_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['logo_id'], ['images.id'], name=op.f('fk_clubs_logo_id_images'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs'))
    )
    op.create_table('groups',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_image_id', sa.Uuid(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('public', 'private')", name=op.f('ck_groups_visibility_allowed')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_groups_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_groups_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_image_id'], ['images.id'], name=op.f('fk_groups_profile_image_id_images'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_table('boats',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('sail_number', sa.String(), nullable=True),
    sa.Column('loa_m', sa.Float(), nullable=True),
    sa.Column('cert_id', sa.Uuid(), nullable=True),
    sa.Column('mbsa_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('club_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cert_id'], ['files.id'], name=op.f('fk_boats_cert_id_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_boats_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mbsa_id'], ['files.id'], name=op.f('fk_boats_mbsa_id_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boats'))
    )
    op.create_table('regattas',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=True),
    sa.Column('scoring_system', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("scoring_system IN ('low_point', 'bonus_point', 'custom')", name=op.f('ck_regattas_scoring_system_allowed')),
    sa.CheckConstraint("status IN ('scheduled', 'active', 'completed')", name=op.f('ck_regattas_status_allowed')),
    sa.ForeignKeyConstraint(['class_id'], ['boat_classes.id'], name=op.f('fk_regattas_class_id_boat_classes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_regattas_club_id_clubs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regattas'))
    )
    op.create_table('user_clubs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('invited', 'active', 'deleted')", name=op.f('ck_user_clubs_status_allowed')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_user_clubs_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_clubs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_clubs')),
    sa.UniqueConstraint('user_id', 'club_id', name=op.f('uq_user_clubs_user_id_club_id'))
    )
    op.create_table('user_groups',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name=op.f('ck_user_groups_role_allowed')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_user_groups_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_groups_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_groups')),
    sa.UniqueConstraint('user_id', 'group_id', name=op.f('uq_user_groups_user_id_group_id'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('scope_club_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_club_id'], ['clubs.id'], name=op.f('fk_user_roles_scope_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_club_id', name=op.f('uq_user_roles_user_id_role_id_scope_club_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_table('boat_photos',
    sa.Column('boat_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], name=op.f('fk_boat_photos_boat_id_boats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_boat_photos_image_id_images'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boat_photos')),
    sa.UniqueConstraint('boat_id', 'image_id', name=op.f('uq_boat_photos_boat_id_image_id'))
    )
    op.create_table('devices',
    sa.Column('device_type_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('owner_boat_id', sa.Uuid(), nullable=True),
    sa.Column('owner_club_id', sa.Uuid(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('claim_code', sa.String(), nullable=True),
    sa.Column('claim_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.Uuid(), nullable=True),
    sa.Column('api_key_hash', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('unclaimed', 'claimed', 'revoked')", name=op.f('ck_devices_status_allowed')),
    sa.CheckConstraint('num_nonnulls(owner_user_id, owner_boat_id, owner_club_id) <= 1', name=op.f('ck_devices_owner_at_most_one')),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], name=op.f('fk_devices_claimed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_types.id'], name=op.f('fk_devices_device_type_id_device_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_boat_id'], ['boats.id'], name=op.f('fk_devices_owner_boat_id_boats'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_club_id'], ['clubs.id'], name=op.f('fk_devices_owner_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_devices_owner_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('api_key_hash', name=op.f('uq_devices_api_key_hash')),
    sa.UniqueConstraint('claim_code', name=op.f('uq_devices_claim_code')),
    sa.UniqueConstraint('external_id', name=op.f('uq_devices_external_id'))
    )
    op.create_table('race_days',
    sa.Column('regatta_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['regatta_id'], ['regattas.id'], name=op.f('fk_race_days_regatta_id_regattas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_days'))
    )
    op.create_table('user_boats',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('boat_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('default_sailing_role', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("default_sailing_role IN ('skipper', 'crew')", name=op.f('ck_user_boats_default_sailing_role_allowed')),
    sa.CheckConstraint("role IN ('owner', 'admin', 'visitor')", name=op.f('ck_user_boats_role_allowed')),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], name=op.f('fk_user_boats_boat_id_boats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_boats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_boats')),
    sa.UniqueConstraint('user_id', 'boat_id', name=op.f('uq_user_boats_user_id_boat_id'))
    )
    op.create_table('races',
    sa.Column('race_day_id', sa.Uuid(), nullable=False),
    sa.Column('race_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'started', 'finished', 'abandoned')", name=op.f('ck_races_status_allowed')),
    sa.ForeignKeyConstraint(['race_day_id'], ['race_days.id'], name=op.f('fk_races_race_day_id_race_days'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_races')),
    sa.UniqueConstraint('race_day_id', 'race_number', name=op.f('uq_races_race_day_id_race_number'))
    )
    op.create_table('activities',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=True),
    sa.Column('race_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("type IN ('race', 'training', 'solo')", name=op.f('ck_activities_type_allowed')),
    sa.CheckConstraint("visibility IN ('public', 'club', 'group', 'private')", name=op.f('ck_activities_visibility_allowed')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_activities_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_activities_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_activities_group_id_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_activities_race_id_races'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_table('marks',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('mark_role', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("mark_role IN ('pin', 'rc', 'windward', 'leeward', 'gate_port', 'gate_stbd', 'offset', 'drill')", name=op.f('ck_marks_mark_role_allowed')),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_marks_activity_id_activities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marks'))
    )
    op.create_index(op.f('ix_marks_activity_id'), 'marks', ['activity_id'], unique=False)
    op.create_table('sessions',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('boat_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'processed', 'failed')", name=op.f('ck_sessions_status_allowed')),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_sessions_activity_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], name=op.f('fk_sessions_boat_id_boats'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_activity_id'), 'sessions', ['activity_id'], unique=False)
    op.create_index(op.f('ix_sessions_boat_id'), 'sessions', ['boat_id'], unique=False)
    op.create_table('polar_points',
    sa.Column('class_id', sa.Uuid(), nullable=True),
    sa.Column('boat_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('twa_deg', sa.Float(), nullable=False),
    sa.Column('tws_kts', sa.Float(), nullable=False),
    sa.Column('speed_kts', sa.Float(), nullable=False),
    sa.Column('vmg_kts', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("source IN ('reference', 'empirical')", name=op.f('ck_polar_points_source_allowed')),
    sa.CheckConstraint('num_nonnulls(class_id, boat_id, session_id) = 1', name=op.f('ck_polar_points_owner_exactly_one')),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], name=op.f('fk_polar_points_boat_id_boats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['boat_classes.id'], name=op.f('fk_polar_points_class_id_boat_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_polar_points_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polar_points'))
    )
    op.create_table('results',
    sa.Column('race_id', sa.Uuid(), nullable=False),
    sa.Column('boat_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('finish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elapsed_time', sa.Integer(), nullable=True),
    sa.Column('corrected_time', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('finished', 'dnf', 'dns', 'dsq', 'ocs', 'ret')", name=op.f('ck_results_status_allowed')),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], name=op.f('fk_results_boat_id_boats'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_results_race_id_races'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_results_session_id_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results')),
    sa.UniqueConstraint('race_id', 'boat_id', name=op.f('uq_results_race_id_boat_id'))
    )
    op.create_table('session_crew',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sailing_role', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sailing_role IN ('skipper', 'crew', 'guest')", name=op.f('ck_session_crew_sailing_role_allowed')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_crew_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_session_crew_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_crew')),
    sa.UniqueConstraint('session_id', 'user_id', name=op.f('uq_session_crew_session_id_user_id'))
    )
    op.create_index(op.f('ix_session_crew_session_id'), 'session_crew', ['session_id'], unique=False)
    op.create_table('session_photos',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_session_photos_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_session_photos_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_photos_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_photos')),
    sa.UniqueConstraint('session_id', 'image_id', name=op.f('uq_session_photos_session_id_image_id'))
    )
    op.create_table('session_stats',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('avg_speed_kts', sa.Float(), nullable=True),
    sa.Column('max_speed_kts', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('avg_polar_pct', sa.Float(), nullable=True),
    sa.Column('max_polar_pct', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_stats_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_session_stats'))
    )
    op.create_table('session_uploads',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('import_id', sa.Uuid(), nullable=True),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_user_id', sa.Uuid(), nullable=True),
    sa.Column('raw_ref', sa.String(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("(source_type = 'device' AND device_id IS NOT NULL AND import_id IS NULL) OR (source_type = 'manual_import' AND import_id IS NOT NULL AND device_id IS NULL)", name=op.f('ck_session_uploads_source_consistent')),
    sa.CheckConstraint("source_type IN ('device', 'manual_import')", name=op.f('ck_session_uploads_source_type_allowed')),
    sa.CheckConstraint("status IN ('pending', 'processing', 'processed', 'failed')", name=op.f('ck_session_uploads_status_allowed')),
    sa.CheckConstraint("subject_type = 'crew_member' OR subject_user_id IS NULL", name=op.f('ck_session_uploads_subject_consistent')),
    sa.CheckConstraint("subject_type IN ('boat', 'crew_member')", name=op.f('ck_session_uploads_subject_type_allowed')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_session_uploads_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name=op.f('fk_session_uploads_import_id_imports'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_uploads_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], name=op.f('fk_session_uploads_subject_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_uploads')),
    sa.UniqueConstraint('session_id', 'device_id', 'sequence_number', name=op.f('uq_session_uploads_session_id_device_id_sequence_number'))
    )
    op.create_index(op.f('ix_session_uploads_session_id'), 'session_uploads', ['session_id'], unique=False)
    op.create_table('session_videos',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_session_videos_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_session_videos_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_videos_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_videos')),
    sa.UniqueConstraint('session_id', 'file_id', name=op.f('uq_session_videos_session_id_file_id'))
    )
    op.create_table('session_streams',
    sa.Column('session_upload_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_type', sa.String(), nullable=False),
    sa.Column('sample_rate_hz', sa.Float(), nullable=True),
    sa.Column('data_ref', sa.String(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("sensor_type IN ('gps', 'imu', 'wind', 'pressure', 'heart_rate', 'other')", name=op.f('ck_session_streams_sensor_type_allowed')),
    sa.ForeignKeyConstraint(['session_upload_id'], ['session_uploads.id'], name=op.f('fk_session_streams_session_upload_id_session_uploads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_streams'))
    )
    op.create_index(op.f('ix_session_streams_session_upload_id'), 'session_streams', ['session_upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_profile_image_id_images'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_session_streams_session_upload_id'), table_name='session_streams')
    op.drop_table('session_streams')
    op.drop_table('session_videos')
    op.drop_index(op.f('ix_session_uploads_session_id'), table_name='session_uploads')
    op.drop_table('session_uploads')
    op.drop_table('session_stats')
    op.drop_table('session_photos')
    op.drop_index(op.f('ix_session_crew_session_id'), table_name='session_crew')
    op.drop_table('session_crew')
    op.drop_table('results')
    op.drop_table('polar_points')
    op.drop_index(op.f('ix_sessions_boat_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_activity_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_marks_activity_id'), table_name='marks')
    op.drop_table('marks')
    op.drop_table('activities')
    op.drop_table('races')
    op.drop_table('user_boats')
    op.drop_table('race_days')
    op.drop_table('devices')
    op.drop_table('boat_photos')
    op.drop_table('user_roles')
    op.drop_table('user_groups')
    op.drop_table('user_clubs')
    op.drop_table('regattas')
    op.drop_table('boats')
    op.drop_table('groups')
    op.drop_table('clubs')
    op.drop_table('boat_classes')
    op.drop_table('wind_observations')
    op.drop_table('role_permissions')
    op.drop_table('imports')
    op.drop_table('images')
    op.drop_table('files')
    op.drop_index(op.f('ix_auth_refresh_tokens_user_id'), table_name='auth_refresh_tokens')
    op.drop_index(op.f('ix_auth_refresh_tokens_token_hash'), table_name='auth_refresh_tokens')
    op.drop_index(op.f('ix_auth_refresh_tokens_family_id'), table_name='auth_refresh_tokens')
    op.drop_table('auth_refresh_tokens')
    op.drop_table('wind_stations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('device_types')
    # ### end Alembic commands ###
